version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=testing
    ports:
      - 5432:5432
    volumes:
      - /home/jcgp/Escritorio/apolloServer1/pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=testingredis
    ports:
      - 6379:6379
    volumes:
      - /home/jcgp/Escritorio/apolloServer1/rdata:/var/lib/redis/dump.rdb
